[build]
  base = "."    # The directory containing your frontend code
  command = "npm run build"   # The build command for your React app
  publish = "./build"    # The directory to publish (output of the build process)

[[plugins]]
  package = "netlify-plugin-cache"

[[plugins]]
  package = "netlify-plugin-inline-functions"
