[build]
command = "npm run build"
publish="frontend_app/build"
base = "frontend_app"

[[plugins]]
  package = "netlify-plugin-cache"
  package = "netlify-plugin-inline-functions-env"
    [plugins.inputs]
    verbose = "true"
